### ISSUE TITLE
Show user message if they fail to make picklist selection

### ISSUE THREAD

**Issue by programmer2coder** [SFDO-Community-Sprints/Salesforce-Indicators#112]
When I dragged the LWC to my Lightning Page Layout, I (oops yeah I know my mistake) neglected to make that very first picklist selection to pick "Please select indicator Bundle".  Jodie was easily able to troubleshoot my omission, and asked me to post an issue here so that maybe you could **display some kind of reminder** for anyone who makes the same omission that I did (instead of just seeing a blank component on the page layoue).

**Comment by programmer2coder** [comment]
Hi @JodieM , I "assigned" you this issue just so you could review it before it lands in somebody else's lap.  Thanks for all your help today!! -Eileen

**Comment by tschug** [comment]
Addressed.  Thanks!
