### ISSUE TITLE
Permission Sets

### ISSUE THREAD

**Issue by JodieM** [SFDO-Community-Sprints/Salesforce-Indicators#116]
To be complete we need to add the following to the "Indicators Setup Access" permission set

* CMDT Read, Create, Edit, Delete
* Apex Classes

And create a new permission set for "Indicators Read Access"
* CMDT Read
* Apex Classes

**Comment by tschug** [comment]
Completed by adding "Indicators User Access" - which users only need Apex access, not CMDT (I don't know if you can limit CRUD on it)
