### ISSUE TITLE
Better error message for Invalid Fields

### ISSUE THREAD

**Issue by JodieM** [SFDO-Community-Sprints/Salesforce-Indicators#25]
![image](https://user-images.githubusercontent.com/2966583/86760501-9b313500-c088-11ea-94e2-21a0a3f4cb48.png)
Need to use the SLDS appropriate error message styling

**Comment by JodieM** [comment]
Note: This one is fixed by CMDT (#10) and I've also added a ticket for any other error messaging that needs to be done (#46)

**Comment by tschug** [comment]
Closed - will be addressed by #46
