### ISSUE TITLE
Greater than 0

### ISSUE THREAD

**Issue by JodieM** [SFDO-Community-Sprints/Salesforce-Indicators#36]
Currently the Indicators only work on Text values or Boolean values. That is a bit limiting because to do something like **Is Donor** from the NPSPs rollup of Total No. of Gifts or Total Value of Gifts then you have to add another field to turn that count or dollar value into a Boolean. Whereas if we had an option to say ``npo02__NumberOfClosedOpps__c`` is ``Greater than 0`` then we save the users having to create another field just for the Indicator. 

This also works well in conjunction with DLRS eg counting the No. of Contacts, No. of Cases, No. of Open Opps to drive indicators like Has Contacts, Has Cases, Has Open Opps.

**Comment by JodieM** [comment]
An option is to extend Show when False or Blank to Show when False or Blank or Zero and if that is false, then it doesn't show. This way it is way simpler than Extensions.

**Comment by JodieM** [comment]
Ah, actually I don't think that works... (I tried it and I could not get it to work)

```...(dataValue === false || dataValue === null || dataValue === '' || dataValue === 0) && definition.showFalse ? {```

**Comment by tschug** [comment]
I thought I replied, but now I cannot find it.

My thinking is that we add a picklist (or checkbox) to determine how to treat Zeros (similar to how there is ['Blank Field Handling' in formula fields](https://help.salesforce.com/s/articleView?id=000381641&type=1)) .

It will take a moment to explain, but it makes sense.

For fields that are blank - we already have the checkbox `Show when False or Blank`

1. If you want to ignore blanks/false - you do not check the box.
2. If you want to handle the blanks/false - you do check the box.

For fields that have zero - we can leverage the same `Show when False or Blank` checkbox plus the new picklist option:
1. If your numeric field is blank - it's governed by the `Show when False or Blank` checkbox already.
2. If your numeric field is Zero, and you set it to `Treat Zeros as Blank` then it will depend on the `Show when False or Blank` checkbox to either ignore it or use the inverse values.
3. If your numeric field is Zero, and you want to utilize it, then use `Treat Zeros as Zeros` and it will follow the existing behavior of the Indicator Item or it's Extensions (you can set the Minimum to be 0 and the Maximum to be 1 or 0.001.

**Comment by JodieM** [comment]
Yes, I like it. Allows for the Extensions to be used. But try ```Treat Zeros as Number``` as Treat Zeros as Zeros sounds weird.
