### ISSUE TITLE
Custom Colour Icon

### ISSUE THREAD

**Issue by JodieM** [SFDO-Community-Sprints/Salesforce-Indicators#71]
Instead of entering a Salesforce Icon colour, be able to enter a hex colour value to have the Icon show as that colour. 
It works with ```style="background:#000000;"``` but I don't know if there is a better way now with [Styling Hooks](https://developer.salesforce.com/docs/component-library/documentation/en/lwc/lwc.create_components_css_custom_properties)  or similar

**Comment by tschug** [comment]
See CSS here.
https://github.com/claireSFDC/Personal_Work/tree/main/iconDisplayFlow
