### ISSUE TITLE
Apex Tests

### ISSUE THREAD

**Issue by JodieM** [SFDO-Community-Sprints/Salesforce-Indicators#75]

**Comment by tschug** [comment]
Need to have peer-review that tests are sufficient and not just meeting code coverage.

**Comment by nzgonjanin** [comment]
If you want to do use case test coverage per use case (recipe) you will need to have documented input and output expected values for assertions and create data factory to support creating recodes for use case.
This may be extra work with little value at this time but may reduce regression testing down the road when new features are added.
