### ISSUE TITLE
Less Whitespace

### ISSUE THREAD

**Issue by JodieM** [SFDO-Community-Sprints/Salesforce-Indicators#83]
When we have no heading or no text, or no icon, there is too much whitespace on the card vertically above and below the icons. 

Similar to #27 but that is for space between icons. And the vertical space could be tightened up a bit normally anyway. 

![image](https://user-images.githubusercontent.com/2966583/198998867-9073d65c-7be2-487c-b8ae-6be79783da21.png)

**Comment by tschug** [comment]
I think this is because we're using the Lightning Card - we may need to drop the Card component and just build its concept from scratch based on the SLDS documentation.

**Comment by tschug** [comment]
This is actually a result of "Comfy" vs "Compact" because we are using the "Narrow" variant.

Still a known issue of the card.
