### ISSUE TITLE
Indicators Key Modal

### ISSUE THREAD

**Issue by tschug** [SFDO-Community-Sprints/Salesforce-Indicators#88]
It hit me that we could help users by providing a "key" to what the different indicators mean.  I've done something similar where I placed a link/button that would [open a modal](https://developer.salesforce.com/docs/component-library/bundle/lightning-modal/documentation) (much easier after Winter '23) that would show the icons and a description.

I think that this would be helpful so that new employees of a company could use this feature to be "onboarded" to what indicators they may come across working on records.

Putting it in a modal tucks it away so it's easily brought up, but not taking up much space.

Presumably, we would read all the CMDT indicator records tied to that bundle, and rather than filtering down to the ones that meet field values, we would display them all (replacing any dynamic initials) grouped by field.  So for example, they could see:
- Rating:  🟥 = Hot | 🟨 = Warm
- Industry:  🏥 = Medical | 🏟 = Sports | 🏭 = Manufacturing
- and so on ...

**Comment by JodieM** [comment]
Oh that would be lovely, if it could be done without much more customisation by the Admin.

It would also solve another issue I had where I could not remember what indicators I had set up yet.

**Comment by tschug** [comment]
🎉 This was built during the March 2023 sprint. 🎉
